name: mc-installer
title: Minecraft Installer
version: '7.3'
summary: A simple installer for Minecraft - Java Edition
description: | 
  A simple installer for Minecraft - Java Edition. 
license: MIT

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mc-installer:
    extensions:
      - gnome-3-28
    command: launch
    plugs:
      - network
      - opengl
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      - browser-support
      - home
    environment:
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/dist-packages
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/

parts:
  launcher:
    plugin: dump
    source: scripts

  game:
    plugin: nil
    build-packages:
      - openjdk-8-jre-headless        
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - libglu1-mesa
      - libswt-gtk-3-java
      - python3-requests
      - openjdk-8-jre-headless
      - libxss1
      - libgconf2-4
      - libcurl3
      - python3-gi
  
  cleanup:
    after: 
      - game
      - launcher
    plugin: nil
    build-snaps:  
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
